# [Problem 1] Matrix product is calculated manually

In [1]:
import numpy as np

In [2]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [3]:
a_ndarray

array([[-1,  2,  3],
       [ 4, -5,  6],
       [ 7,  8, -9]])

In [4]:
b_ndarray

array([[ 0,  2,  1],
       [ 0,  2, -8],
       [ 2,  9, -1]])

In [5]:
ab_mult = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]))

In [6]:
for i in range(a_ndarray.shape[0]):
    for j in range(b_ndarray.shape[1]):
        ab_mult[i, j] = np.sum(a_ndarray[i, :]*b_ndarray[:, j])

ab_mult

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

In [7]:
# TODO explanation of matrix multiplication

# [Problem 2] Calculation by NumPy function

In [9]:
ab_matmul = np.matmul(a_ndarray, b_ndarray)
ab_matmul

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [10]:
ab_dot = np.dot(a_ndarray, b_ndarray)
ab_dot

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [11]:
ab_at = a_ndarray@b_ndarray
ab_at

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# [Problem 3] Implementation of calculation of a certain element

In [16]:
a = a_ndarray
b = b_ndarray
ab_mult = np.zeros((a.shape[0], b.shape[1]))

for i in range(a.shape[0]):
    for j in range(b.shape[1]):
        for k in range(b.shape[0]):
            ab_mult[i][j] += a[i][k] * b[k][j]

ab_mult

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

# [Problem 4] Creating a function that performs matrix multiplication

In [20]:
def matrix_multiplication(a, b):

    ## TODO comment

    assert a.shape[0]==b.shape[1], "Matrix dim is not suitable"  #ERROR MSG
    
    ab_mult = np.zeros((a.shape[0], b.shape[1]))
    
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(b.shape[0]):
                ab_mult[i][j] += a[i][k] * b[k][j]

    return ab_mult
        

In [21]:
matrix_multiplication(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

# [Problem 5] Judge the input whose calculation is not defined

In [22]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [23]:
matrix_multiplication(d_ndarray, e_ndarray)

AssertionError: Matrix dim is not suitable

# [Problem 6] Transposition

In [25]:
print(e_ndarray)
np.transpose(e_ndarray)

[[-9  8  7]
 [ 6 -5  4]]


array([[-9,  6],
       [ 8, -5],
       [ 7,  4]])

In [26]:
e_ndarray.T

array([[-9,  6],
       [ 8, -5],
       [ 7,  4]])

In [27]:
matrix_multiplication(d_ndarray, e_ndarray.T)

array([[ 46.,  -4.],
       [-34.,  73.]])